# Generated by Django 2.2.9 on 2020-07-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinpoint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='latitude',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='point',
            name='longitude',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
